# permissions for end users to edit dopplersecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dopplersecret-editor-role
rules:
- apiGroups:
  - secrets.doppler.com
  resources:
  - dopplersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.doppler.com
  resources:
  - dopplersecrets/status
  verbs:
  - get
