# permissions for end users to view dopplersecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dopplersecret-viewer-role
rules:
- apiGroups:
  - secrets.doppler.com
  resources:
  - dopplersecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.doppler.com
  resources:
  - dopplersecrets/status
  verbs:
  - get
