apiVersion: apps/v1
kind: Deployment
metadata:
  name: doppler-test-deployment-volume
  annotations:
    secrets.doppler.com/reload: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doppler-test
  template:
    metadata:
      labels:
        app: doppler-test
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: doppler-test-secret # Kubernetes secret name
      containers:
        - name: doppler-test
          image: alpine
          command: # ['/bin/sh', '-c', 'apk add --no-cache tini > /dev/null 2>&1 && ls /etc/secrets | grep -v KUBERNETES_&& tini -s tail -f /dev/null'] # List all non-Kubernetes secret files
            - /bin/sh
            - -c
            - apk add --no-cache tini > /dev/null 2>&1 &&
              echo "### This is a simple deployment running with these mounted secret files:" &&
              (for f in $(find /etc/secrets -type f); do echo $f && cat $f && echo ""; done) &&
              tini -s tail -f /dev/null
          imagePullPolicy: Always
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
          resources:
            requests:
              memory: '250Mi'
              cpu: '250m'
            limits:
              memory: '500Mi'
              cpu: '500m'
