apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-test # DopplerSecret resource name
  namespace: doppler-operator-system # The Doppler operator namespace (recommended)
spec:
  # Omitted secret reference namespaces will default to match the namespace of the DopplerSecret
  tokenSecretRef: # Reference to Doppler Token Secret
    name: doppler-token-secret
    key: dopplerToken
  managedSecretRef: # Reference to Managed Secret (will be created automatically if does not exist)
    name: doppler-test-secret
    namespace: default # Should match the namespace of deployments which will use the secret
