apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-test # DopplerSecret resource name
spec:
  tokenSecretRef: # Reference to the Kubernetes secret containing your Doppler Service Token
    name: doppler-token-secret
    key: dopplerToken
  managedSecretRef: # Reference to the Kubernetes secret where your Doppler secrets will be synced
    name: doppler-test-secret
