name: Publish to DockerHub
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract Version
        id: extract
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/v}

      - name: Print Version
        run: echo ${{ steps.extract.outputs.version }}

      - name: Print Ref
        run: echo ${GITHUB_REF}
