name: Publish to DockerHub
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract Version
        id: extract
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/v}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            dopplerhq/kubernetes-operator:${{ steps.extract.outputs.version }}
            dopplerhq/kubernetes-operator:latest
          build-args: |
            CONTROLLER_VERSION=${{ steps.extract.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Generate Recommended YAML
        uses: actions/setup-go@v2
        run: make dist

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: YAML Artifacts
          path: ./dist
